### ISSUE TITLE
Got an error for response_hash

### ISSUE THREAD

**Issue by rubyFeedback** [smackdh/glimmer_app#2]
In the .rb file you provided, I just copy/pasted it:

    response_hash['rates'].each do |currency, rate|

I got an error though:

    foobar.rb:38:in `get_data': undefined method `each' for nil:NilClass (NoMethodError)

Perhaps the dataset was not properly downloaded. Do you think you could extend
the .rb file to protect against that error? We may have to add a is-nil aka .nil? check,
and perhaps use another method for the downloading-of-the-dataset. Right now I
don't know how the error came to be, I just downloaded the .rb file, tried to run it
and the above error showed up.

**Comment by mataesu** [comment]
Hi!

Make sure to double check that you have a working API-key set up, as it otherwise won't have any data to iterate over.

But yes, some error handling is definitely a good idea either way.

**Comment by mataesu** [comment]
Updated. Added error handling to log if API-key is missing of fetching goes wrong.
